AM_CXXFLAGS = @CXXFLAGS@ @XFC_UI_CFLAGS@ @XFC_GLADE_CFLAGS@

INCLUDES = \
 -I$(top_builddir)/libXFCcore \
 -I$(top_builddir)/libXFCglade \
 -I$(top_builddir)/libXFCui

LIBS = \
 $(top_builddir)/libXFCcore/xfc/libXFCcore-$(XFC_API_VERSION).la \
 $(top_builddir)/libXFCui/xfc/libXFCui-$(XFC_API_VERSION).la \
 $(top_builddir)/libXFCglade/xfc/libXFCglade-$(XFC_API_VERSION).la
	
include $(top_srcdir)/examples/Makefile.fragment
	
